default_branch: main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme@pcmultlectwithmasterormain

kramdown:
   parse_block_html: true

include:
   - _pages
exclude:
   - vendor
   - setup.sh
   - jekyll.sh
   - .sass-cache
   - Gemfile
   - LICENSE
   - .bundle

timezone: America/Los_Angeles

url: https://ucsb-cs156.github.io # the base hostname & protocol for your site
baseurl: /s22  # the subpath of your site, e.g. "/blog"
github_url: https://github.com/ucsb-cs156/s22



course: "CS156"
qtr: "S22"
qxx: "s22"
quarter: "Spring 2022"

lecture_days_of_week: TR

assigned_text: " assigned"
due_text: " due "

start_week: 1
start_date: 2022-03-27
num_weeks: 10
extra_exam_week: true

cal_dates: >
  [                                                                            
    {"label":"S22 1st day of instruction", "date":"2022-03-27" },
    {"label":"Memorial Day", "date":"2022-05-30" },
    {"label":"S22 instruction ends", "date":"2022-06-03" },
    {"label":"S22 finals start", "date":"2022-06-04" },                     
    {"label":"S22 CS156 FINAL (4pm-7pm)", "date":"2022-06-07" },                      
    {"label":"S22 finals end", "date":"2022-06-10" },                          
    {"label":"S22 qtr ends", "date":"2022-06-10" }                              
  ]


gauchospace_course_page: https://gauchospace.ucsb.edu/courses/course/view.php?id=tbd
github_org_name: ucsb-cs156-s22
github_org_url: https://github.com/ucsb-cs156-s22
gradescope: https://www.gradescope.com/courses/379049

ta_list: "Andrew and Kevin"
ta_list_full: "Andrew Lu and Kevin Heffernan"
mentors_list: "Bryan Z, Andrew P"
discussion_section_times: "4pm,&nbsp;5pm,&nbsp;6pm"
sections: "4pm,&nbsp;5pm,&nbsp;6pm"

mentor_url: https://ucsb-cs56-pconrad-mentors.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048
hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

legacy_wiki_url: https://foo.cs.ucsb.edu/56wiki
legacy_wiki_name: "56wiki"


hwk_drop_lowest: two


hfj_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfj/HFJ_Chapter_"
hfdp_chapter_url_prefix: "http://ucsb-cs56-pconrad.github.io/hfdp/HFDP_Chapter_"


collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  hwkWIP:
    output: true
    permalink: /hwkWIP/:path/
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/
  staff:
    output: true
    permalink: /staff/:path



defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: hwkWIP
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
  -
    scope:
     path: ""
     type: staff
    values:
     layout: staff

  - scope:
     path: ""
     type: pages
    values:
     layout: default

head_scripts:
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
   - /static/js/select_section.js

